// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

// 本文件是 exp_project 表的 DAO 包装入口，供实验项目服务访问。

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// expProjectDao is the data access object for the table exp_project.
// You can define custom methods on it to extend its functionality as needed.
type expProjectDao struct {
	*internal.ExpProjectDao
}

var (
	// ExpProject is a globally accessible object for table exp_project operations.
	ExpProject = expProjectDao{internal.NewExpProjectDao()}
)

// Add your custom methods and functionality below.
