// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

// 本文件是 exp_run 表的 DAO 包装入口，供实验 Run 服务访问。

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// expRunDao is the data access object for the table exp_run.
// You can define custom methods on it to extend its functionality as needed.
type expRunDao struct {
	*internal.ExpRunDao
}

var (
	// ExpRun is a globally accessible object for table exp_run operations.
	ExpRun = expRunDao{internal.NewExpRunDao()}
)

// Add your custom methods and functionality below.
