// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// opsQueueDao is the data access object for the table ops_queue.
// You can define custom methods on it to extend its functionality as needed.
type opsQueueDao struct {
	*internal.OpsQueueDao
}

var (
	// OpsQueue is a globally accessible object for table ops_queue operations.
	OpsQueue = opsQueueDao{internal.NewOpsQueueDao()}
)

// Add your custom methods and functionality below.
