// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// opsQueueTeamDao is the data access object for the table ops_queue_team.
// You can define custom methods on it to extend its functionality as needed.
type opsQueueTeamDao struct {
	*internal.OpsQueueTeamDao
}

var (
	// OpsQueueTeam is a globally accessible object for table ops_queue_team operations.
	OpsQueueTeam = opsQueueTeamDao{internal.NewOpsQueueTeamDao()}
)

// Add your custom methods and functionality below.
