// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// opsNodeEventDao is the data access object for the table ops_node_event.
// You can define custom methods on it to extend its functionality as needed.
type opsNodeEventDao struct {
	*internal.OpsNodeEventDao
}

var (
	// OpsNodeEvent is a globally accessible object for table ops_node_event operations.
	OpsNodeEvent = opsNodeEventDao{internal.NewOpsNodeEventDao()}
)

// Add your custom methods and functionality below.
