// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// opsClusterDao is the data access object for the table ops_cluster.
// You can define custom methods on it to extend its functionality as needed.
type opsClusterDao struct {
	*internal.OpsClusterDao
}

var (
	// OpsCluster is a globally accessible object for table ops_cluster operations.
	OpsCluster = opsClusterDao{internal.NewOpsClusterDao()}
)

// Add your custom methods and functionality below.
