// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// opsAlertDao is the data access object for the table ops_alert.
// You can define custom methods on it to extend its functionality as needed.
type opsAlertDao struct {
	*internal.OpsAlertDao
}

var (
	// OpsAlert is a globally accessible object for table ops_alert operations.
	OpsAlert = opsAlertDao{internal.NewOpsAlertDao()}
)

// Add your custom methods and functionality below.
