// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// sysLdapConfigDao is the data access object for the table sys_ldap_config.
// You can define custom methods on it to extend its functionality as needed.
type sysLdapConfigDao struct {
	*internal.SysLdapConfigDao
}

var (
	// SysLdapConfig is a globally accessible object for table sys_ldap_config operations.
	SysLdapConfig = sysLdapConfigDao{internal.NewSysLdapConfigDao()}
)

// Add your custom methods and functionality below.
