// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// sysTeamMemberDao is the data access object for the table sys_team_member.
// You can define custom methods on it to extend its functionality as needed.
type sysTeamMemberDao struct {
	*internal.SysTeamMemberDao
}

var (
	// SysTeamMember is a globally accessible object for table sys_team_member operations.
	SysTeamMember = sysTeamMemberDao{internal.NewSysTeamMemberDao()}
)

// Add your custom methods and functionality below.
