// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// sysTeamDao is the data access object for the table sys_team.
// You can define custom methods on it to extend its functionality as needed.
type sysTeamDao struct {
	*internal.SysTeamDao
}

var (
	// SysTeam is a globally accessible object for table sys_team operations.
	SysTeam = sysTeamDao{internal.NewSysTeamDao()}
)

// Add your custom methods and functionality below.
