// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// trainConfigVersionDao is the data access object for the table train_config_version.
// You can define custom methods on it to extend its functionality as needed.
type trainConfigVersionDao struct {
	*internal.TrainConfigVersionDao
}

var (
	// TrainConfigVersion is a globally accessible object for table train_config_version operations.
	TrainConfigVersion = trainConfigVersionDao{internal.NewTrainConfigVersionDao()}
)

// Add your custom methods and functionality below.
