// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// trainConfigSetDao is the data access object for the table train_config_set.
// You can define custom methods on it to extend its functionality as needed.
type trainConfigSetDao struct {
	*internal.TrainConfigSetDao
}

var (
	// TrainConfigSet is a globally accessible object for table train_config_set operations.
	TrainConfigSet = trainConfigSetDao{internal.NewTrainConfigSetDao()}
)

// Add your custom methods and functionality below.
