// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// trainConfigDraftDao is the data access object for the table train_config_draft.
// You can define custom methods on it to extend its functionality as needed.
type trainConfigDraftDao struct {
	*internal.TrainConfigDraftDao
}

var (
	// TrainConfigDraft is a globally accessible object for table train_config_draft operations.
	TrainConfigDraft = trainConfigDraftDao{internal.NewTrainConfigDraftDao()}
)

// Add your custom methods and functionality below.
