// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gqcn/ltp/internal/dao/internal"
)

// trainJobDao is the data access object for the table train_job.
// You can define custom methods on it to extend its functionality as needed.
type trainJobDao struct {
	*internal.TrainJobDao
}

var (
	// TrainJob is a globally accessible object for table train_job operations.
	TrainJob = trainJobDao{internal.NewTrainJobDao()}
)

// Add your custom methods and functionality below.
